export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_LOADING = "ADD_MOVIE_LOADING";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";

export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const REMOVE_MOVIE_LOADING = "REMOVE_MOVIE_LOADING";
export const REMOVE_MOVIE_ERROR = "REMOVE_MOVIE_ERROR";

export const EDIT_MOVIE = "EDIT_MOVIE";
export const EDIT_MOVIE_ERROR = "EDIT_MOVIE_ERROR";
export const EDIT_MOVIE_LOADING = "EDIT_MOVIE_LOADING";

export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIES_ERROR = "SET_MOVIES_ERROR";
export const SET_MOVIES_LOADING = "SET_MOVIES_LOADING";
