export const SET_MOVIES_SEARCH = "SET_MOVIES_SEARCH";
export const SET_MOVIES_FILTER = "SET_MOVIES_FILTER";
export const SET_MOVIES_SORTBY = "SET_MOVIES_SORTBY";
export const SET_MOVIES_ORDER = "SET_MOVIES_ORDER";

export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_LOADING = "ADD_MOVIE_LOADING";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";

export const DELETE_MOVIE = "DELETE_MOVIE";
export const DELETE_MOVIE_LOADING = "DELETE_MOVIE_LOADING";
export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";

export const EDIT_MOVIE = "ADD_MOVIE";
export const EDIT_MOVIE_LOADING = "ADD_MOVIE_LOADING";
export const EDIT_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const EDIT_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";

export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const REMOVE_MOVIE_LOADING = "REMOVE_MOVIE_LOADING";
export const REMOVE_MOVIE_ERROR = "REMOVE_MOVIE_ERROR";

export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIES_ERROR = "SET_MOVIES_ERROR";
export const SET_MOVIES_LOADING = "SET_MOVIES_LOADING";
